const fs = require('fs');
const path = require('path');
const assert = require('assert');
const root = path.resolve(__dirname, '..', '..');
const app = fs.readFileSync(path.join(root, 'src', 'app.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'src', 'styles.css'), 'utf8');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');

assert(app.includes("id: 'myAccount'"), 'Security/My Account navigation must exist.');
assert(app.includes("id: 'adminAccounts'"), 'Owner-only Admin Accounts navigation must exist.');
assert(app.includes("id: 'systemOwnership'"), 'Owner-only System Ownership navigation must exist.');
assert(app.includes('state.adminSession?.systemOwner'), 'Owner-only pages must be hidden and blocked client-side.');
assert(app.includes('/api/admin/invitations'), 'Invite-only endpoints must be wired.');
assert(app.includes('/api/admin/account/security/revoke-sessions'), 'Self session revocation must be wired.');
assert(app.includes('/api/admin/account/security/password-reset/request'), 'Forgot password must use the backend eligibility gate.');
assert(app.includes('publicApi(API_PATHS.admin.requestPasswordReset'), 'Forgot password must remain usable before sign-in.');
assert(!app.includes("'accounts:sendOobCode'"), 'Admin web must not bypass backend eligibility by sending Firebase reset emails directly.');
assert(app.includes('If an eligible admin account exists, reset instructions have been sent.'), 'Forgot password must resist account enumeration.');
assert(app.includes('accounts/mfaEnrollment:start'), 'TOTP enrollment start must use Firebase Identity Platform.');
assert(app.includes('accounts/mfaEnrollment:finalize'), 'TOTP enrollment finalize must use Firebase Identity Platform.');
assert(app.includes('state.totpEnrollment'), 'TOTP secret must remain ephemeral browser state.');
assert(app.includes('handlePendingGovernanceLink'), 'Invitation/owner target links must complete after exact-email Firebase sign-in.');
assert(app.includes('governanceMfaRequired'), 'A new ownership target must have a dedicated pre-admin MFA onboarding state.');
assert(app.includes('renderOwnerTransferMfaOnboarding'), 'Owner target MFA enrollment must be usable before the target becomes an admin.');
assert(app.includes("loadBackendSession: false"), 'Target TOTP enrollment must not require an existing Backend admin session.');
assert(app.includes("nextTab !== 'myAccount'"), 'MFA-required admins must be locked to My Account until MFA is satisfied.');
assert(app.includes('protectedOwnerTransferAction'), 'Owner verify/commit must require reauthentication and MFA.');
assert(app.includes('Final atomic commit'), 'Ownership UI must clearly identify the irreversible final commit.');
assert(css.includes('.governance-page'), 'Governance pages must have dedicated responsive styling.');
assert(css.includes('.sensitive-secret-box'), 'TOTP secret must have a clear sensitive-data treatment.');
assert(html.includes('20260710-admin-governance-v1'), 'Governance runtime must be cache-busted.');
console.log('PASS admin account governance web audit');
